services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: naneandreasyan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nats:
    image: nats:2.11
    container_name: nats-server
    ports:
      - "4222:4222"

  app:
    build: .
    depends_on:
      - postgres
      - nats
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/messaging
      DB_USER: naneandreasyan
      DB_PASSWORD: 1234
      NATS_URL: nats://nats-server:4222
    restart: on-failure

volumes:
  pgdata: